### ISSUE TITLE
Build status badges aren't properly displayed

### ISSUE THREAD

**Issue by MikeChemi** [microsoft/spatialaudio-unity#10]
Claims master branch never built, and image for develop branch is not showing for me.

**Comment by keveleigh** [comment]
Looks like the master branch badge is fixed in https://github.com/microsoft/spatialaudio-unity/pull/9, but the develop badge isn't resolving due to the project the pipeline is hosted in being private 
![image](https://user-images.githubusercontent.com/3580640/96064266-d17f0d00-0e4c-11eb-8335-c3582322c897.png)

**Comment by ashtat** [comment]
Thanks for that hint @keveleigh! Fixed now.
