### ISSUE TITLE
package update

### ISSUE THREAD

**Issue by Daniel4144** [microsoft/spatialaudio-unity#88]
Will there be a package update in the near future or is this project dead?

I reported an issue over a year ago and it got closed with the notice that it will be fixed with the next update, but this never happened (https://github.com/microsoft/spatialaudio-unity/issues/83).

**Comment by NoelCross** [comment]
@Daniel4144 this project has not had much active development recently, although having said that, the spatializer processing DSP is still using the latest efficient rendering algorithms that are shipped in Windows and Xbox.  Since this project is open source, other than the DSP module, feel free to provide a PR for the metadata update that you highlighted and we can approve this for everyone to benefit.  Thanks for your interest in this project.

**Comment by Daniel4144** [comment]
Since the PR was accepted, will the package be updated eventually?
Now the fix is in the repo source, but neither the github release nor the latest package from the Mixed Reality Feature Tool benefit from it.

**Comment by NoelCross** [comment]
@Daniel4144 Thank you for the reminder.  It took a little bit of time to dust off the build pipeline since it hadn't been run in a year, but now I have published the new package 2.0.47 with your update.  I didn't update the sample yet to point to the new version, but at least now it shows up in the MR Feature Tool:

<img width="190" alt="image" src="https://github.com/microsoft/spatialaudio-unity/assets/19439257/529ab12f-34a1-4d47-b53f-e94cd5607849">
